export const editorial = {
  problemsTitle: 'Biznesingiz hali ham qo‘lda boshqariladimi?',
  problems: [
    'Buyurtmalar qo‘lda qabul qilinadi',
    'Mijozlarga javob berish ko‘p vaqt oladi',
    'Ma’lumotlar turli joylarda saqlanadi',
    'Xodimlar bir xil ishlarni takrorlaydi',
    'Hisobotlar qo‘lda tayyorlanadi',
    'Mijozlarni nazorat qilish qiyin',
  ],
  problemsAnswer: 'Biz bularni tizimga aylantiramiz.',
  complexityTitle: 'Oddiy g‘oyadan murakkab tizimgacha.',
  complexityText: 'Vazifa qanchalik murakkab bo‘lmasin, biz texnologik yechim topamiz.',
  layers: [
    'Telegram Bot',
    'Web Application',
    'CRM',
    'Business Automation',
    'AI Systems',
    'High-load Platforms',
    'Custom Software',
  ],
  processTitle: 'Qanday ishlaymiz?',
  steps: [
    ['Tahlil', 'Biznesingiz, vazifangiz va maqsadlaringizni o‘rganamiz.'],
    ['Strategiya', 'Yechim arxitekturasi, bosqichlar va natijani kelishib olamiz.'],
    ['Development', 'Mahsulotni yaratamiz, sinaymiz va siz bilan birga takomillashtiramiz.'],
    ['Launch & Support', 'Tizimni ishga tushiramiz va keyingi rivojlanishda yoningizda bo‘lamiz.'],
  ],
  benefitsTitle: 'Koddan ko‘proq. Biznes uchun natija.',
  benefits: [
    [
      'Vaqtingiz o‘zingizga',
      'Takroriy ishlar avtomatlashtiriladi. Jamoangiz muhim vazifalarga e’tibor beradi.',
    ],
    ['Aniq ko‘rinish', 'Ma’lumotlar bir joyda. Qarorlar taxmin bilan emas, dalillar asosida.'],
    ['O‘sishga tayyor', 'Yangi jarayonlar va integratsiyalar uchun mustahkam texnologik asos.'],
  ],
  whyTitle: 'Nega BUHARIY TECH?',
  why: [
    'Biznesni tushunamiz',
    'Individual yechim',
    'Zamonaviy texnologiyalar',
    'Skalalanadigan tizimlar',
    'Yuqori darajadagi mutaxassislar',
    'Uzoq muddatli qo‘llab-quvvatlash',
  ],
  story:
    'Buxoro asrlar davomida ilm, savdo, hunarmandchilik va qadriyatlar chorrahasi bo‘lib kelgan. BUHARIY TECH ana shu merosni zamonaviy texnologiyalar bilan davom ettiradi.',
  pricingTitle: 'Moslashuvchan narxlash',
  pricing:
    'Har bir loyiha o‘z vazifasi, murakkabligi va maqsadiga ega. Shuning uchun narx ham individual belgilanadi.',
  pricingSecond:
    'Sifat, vazifa va loyiha murakkabligiga qarab eng maqbul yechimni birgalikda belgilaymiz.',
  cta: 'Biznesingizni keyingi bosqichga olib chiqishga tayyormisiz?',
  ctaText: 'G‘oyangiz bo‘lsa, biz uni ishlaydigan raqamli yechimga aylantiramiz.',
  teamEmpty: 'Jamoa a’zolari haqida ma’lumot tez orada qo‘shiladi.',
  concept: 'Concept Project',
  conceptNotice: 'Bu namoyish konsepti. Haqiqiy mijoz loyihasi yoki o‘lchangan natija emas.',
};
export const formCopy = {
  uz: {
    name: 'Ismingiz',
    phone: 'Telefon raqamingiz',
    telegram: 'Telegram username',
    company: 'Kompaniya',
    service: 'Qaysi xizmat kerak?',
    budget: 'Taxminiy budjet',
    description: 'Loyihangiz haqida',
    hint: 'Qanday vazifani hal qilmoqchisiz? Kamida 20 belgi.',
    optional: 'ixtiyoriy',
    consent: 'Men maxfiylik siyosatiga roziman.',
    submit: 'Ariza yuborish',
    sending: 'Yuborilmoqda…',
    success: 'Arizangiz qabul qilindi.',
    successText: 'Rahmat! Jamoamiz murojaatingizni ko‘rib chiqadi va siz bilan bog‘lanadi.',
    again: 'Yana ariza yuborish',
    error: 'Ariza yuborilmadi. Iltimos, qayta urinib ko‘ring.',
    note: 'Har bir loyiha individual baholanadi.',
  },
  ru: {
    name: 'Ваше имя',
    phone: 'Номер телефона',
    telegram: 'Telegram',
    company: 'Компания',
    service: 'Какая услуга нужна?',
    budget: 'Примерный бюджет',
    description: 'О вашем проекте',
    hint: 'Какую задачу нужно решить? Не менее 20 символов.',
    optional: 'необязательно',
    consent: 'Я согласен с политикой конфиденциальности.',
    submit: 'Отправить заявку',
    sending: 'Отправляем…',
    success: 'Заявка принята.',
    successText: 'Спасибо! Команда рассмотрит заявку и свяжется с вами.',
    again: 'Отправить ещё одну заявку',
    error: 'Не удалось отправить. Попробуйте ещё раз.',
    note: 'Каждый проект оценивается индивидуально.',
  },
  en: {
    name: 'Your name',
    phone: 'Phone number',
    telegram: 'Telegram username',
    company: 'Company',
    service: 'What do you need?',
    budget: 'Estimated budget',
    description: 'About your project',
    hint: 'What challenge would you like to solve? At least 20 characters.',
    optional: 'optional',
    consent: 'I agree to the privacy policy.',
    submit: 'Send request',
    sending: 'Sending…',
    success: 'Your request has been received.',
    successText: 'Thank you. Our team will review your request and contact you.',
    again: 'Send another request',
    error: 'Could not send your request. Please try again.',
    note: 'Every project is priced individually.',
  },
};
