export const solutionCopy = {
  uz: {
    all: 'Barcha yo‘nalishlar',
    sectors: {
      FINANCE: 'Moliya va filiallar',
      MANUFACTURING: 'Ishlab chiqarish',
      TRADE: 'Savdo',
      SERVICES: 'Xizmatlar',
    },
    available: 'Mavjud mahsulot',
    concept: 'Yechim konsepsiyasi',
    for: 'Kimlar uchun',
    included: 'Imkoniyatlar',
    proposed: 'Taklif etilgan modullar',
    details: 'Jarayon va tafsilotlar',
    flow: 'Hisob-kitobdan natijagacha',
    price: 'Tarkibga qarab baholanadi',
    action: 'Joriy etishni muhokama qilish',
    conceptAction: 'Yechimni muhokama qilish',
    budgetTitle: 'Budjetingizga mos tarkib.',
    budgetBody:
      'Kerakli modullar, moslashtirish, ishga tushirish va qo‘llab-quvvatlash shartlarini oldindan kelishamiz.',
    steps: ['Ehtiyoj va modullar', 'Moslashtirish va tekshirish', 'Ishga tushirish va o‘rgatish'],
    selected: 'Tanlangan yechim',
    interest: 'Biznesim uchun ushbu yechimni muhokama qilmoqchiman',
    planned: 'Taklif etilgan yechim konsepsiyasini muhokama qilmoqchiman',
    nav: 'Yechimlar',
  },
  ru: {
    all: 'Все направления',
    sectors: {
      FINANCE: 'Финансы и филиалы',
      MANUFACTURING: 'Производство',
      TRADE: 'Торговля',
      SERVICES: 'Услуги',
    },
    available: 'Продукт компании',
    concept: 'Концепция решения',
    for: 'Для кого',
    included: 'Возможности',
    proposed: 'Предлагаемые модули',
    details: 'Процесс и подробности',
    flow: 'От расчёта до результата',
    price: 'Стоимость зависит от состава',
    action: 'Обсудить внедрение',
    conceptAction: 'Обсудить решение',
    budgetTitle: 'Состав под ваш бюджет.',
    budgetBody: 'Заранее согласуем нужные модули, адаптацию, запуск и условия поддержки.',
    steps: ['Задачи и модули', 'Настройка и проверка', 'Запуск и обучение'],
    selected: 'Выбранное решение',
    interest: 'Хочу обсудить применение решения в моём бизнесе',
    planned: 'Хочу обсудить предлагаемую концепцию решения',
    nav: 'Решения',
  },
  en: {
    all: 'All solutions',
    sectors: {
      FINANCE: 'Finance & branches',
      MANUFACTURING: 'Manufacturing',
      TRADE: 'Trade',
      SERVICES: 'Services',
    },
    available: 'Company product',
    concept: 'Solution concept',
    for: 'Who it is for',
    included: 'Capabilities',
    proposed: 'Proposed modules',
    details: 'Workflow and details',
    flow: 'From estimate to outcome',
    price: 'Price depends on scope',
    action: 'Discuss implementation',
    conceptAction: 'Discuss this solution',
    budgetTitle: 'A scope that fits your budget.',
    budgetBody: 'We agree on the modules, adaptation, launch and support terms before work begins.',
    steps: ['Needs and modules', 'Adaptation and testing', 'Launch and training'],
    selected: 'Selected solution',
    interest: 'I would like to discuss using this solution for my business',
    planned: 'I would like to discuss this proposed solution concept',
    nav: 'Solutions',
  },
};
